#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "c-async-test"
version = "0.1.0"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "ctest"

[component.ctest]
source = "test.wasm"
allowed_outbound_hosts = []
[component.ctest.build]
command = "$WASI_SDK_PATH/bin/wasm32-wasip2-clang --sysroot=$WASI_SDK_PATH/share/wasi-sysroot test.c bindings/http_trigger.c bindings/http_trigger_component_type.o -mexec-model=reactor -o test.wasm"
watch = ["**/*.c"]
